[package]
name = "rusk-abi"
version = "0.12.0-rc.0"
edition = "2021"

repository = "https://github.com/dusk-network/rusk"
description = "The ABI to develop Dusk Network smart contracts"
license = "MPL-2.0"
exclude = [".github/workflows/ci.yml", ".gitignore"]

[dependencies]
blake2b_simd = { version = "1", default-features = false }
cfg-if = "1"

bls12_381-bls = { version = "0.1", features = ["rkyv-impl"] }
bytecheck = { version = "0.6", default-features = false }
dusk-bytes = "0.1"
dusk-bls12_381 = { version = "0.13", default-features = false, features = ["rkyv-impl"] }
dusk-jubjub = { version = "0.14", default-features = false, features = ["rkyv-impl"] }
dusk-plonk = { version = "0.19", default-features = false, features = ["rkyv-impl", "alloc"] }
dusk-poseidon = { version = "0.33", default-features = false }
jubjub-schnorr = { version = "0.1", default-features = false, features = ["rkyv-impl"] }
phoenix-core = { version = "0.25.0-rc.0", default-features = false, features = ["rkyv-impl", "alloc"] }

piecrust-uplink = "0.9.0-rc"
piecrust = { version = "0.14.0-rc", optional = true }

# These are patches since these crates don't seem to like semver.
rkyv = { version = "=0.7.39", default-features = false }
wasmer = { version = "=3.1", optional = true }

[dev-dependencies]
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
once_cell = "1.15"
ff = { version = "0.13", default-features = false }

[features]
# By default, we include the contract writing features.
default = ["abi", "dlmalloc"]

# These are the features available for when one wishes to use `rusk-abi` as a
# contract.
abi = ["piecrust-uplink/abi"]
debug = ["abi", "piecrust-uplink/debug"]
dlmalloc = ["piecrust-uplink/dlmalloc"]

# These are the features available for when one wishes to use `rusk-abi` as a
# host.
host = ["piecrust"]
host_debug = ["piecrust/debug"]

[[test]]
name = "test-rusk-abi"
path = "tests/lib.rs"
required-features = ["host"]
