[package]
name = "stake-contract-types"
description = "Stake contract types for the Dusk Network."
version = "0.0.1-rc.2"
edition = "2021"
license = "MPL-2.0"

[dependencies]
dusk-bls12_381 = { version = "0.13", default-features = false, features = ["rkyv-impl"] }
bls12_381-bls = { version = "0.1", default-features = false, features = ["rkyv-impl"] }
dusk-bytes = "0.1"
phoenix-core = { version = "0.25.0-rc.0", default-features = false, features = ["rkyv-impl", "alloc"] }

rkyv = { version = "0.7", default-features = false, features = ["size_32"] }
bytecheck = { version = "0.6", default-features = false }
