[package]
name = "node-data"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-bls12_381 = "0.13"
phoenix-core = { version = "0.25.0-rc.0", features = ["alloc"] }
dusk-bytes = "^0.1"
bytes = "0.6"
sha3 = "0.10"
sha2 = "0.10"
fake = { version = "2.5", features = ['derive'], optional = true }
rand = { version = "0.8", optional = true }
hex = { version = "0.4", optional = true }
bls12_381-bls = { version = "0.1", default-features = false }
rusk-abi = { version = "0.12.0-rc", path = "../rusk-abi", default-features = false }

rand_core = { version = "0.6", default-features = false }
blake3 = "1.3"
block-modes = "0.8"
aes = "0.7"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.13"
async-channel = "1.7"
chrono = "0.4"
bs58 = { version = "0.4" }
tracing = "0.1"


[dev-dependencies]
fake = { version = "2.5", features = ['derive'] }
rand = "0.8"
hex = "0.4"

[features]
default = ["dep:rand", "dep:hex"]
faker = ["dep:fake", "dep:rand", "dep:hex"]
